export const actions = {
    profile:{
        DATA_LOADING: "PROFILE_DATA_LOADING",
        DATA_LOADED: "PROFILE_DATA_LOADED",
        DATA_LOAD_ERROR: "PROFILE_DATA_LOAD_ERROR",
        USER_DATA_UPDATED: "PROFILE_USER_DATA_UPDATED",
        USER_IMAGE_UPDATED: "PROFILE_USER_IMAGE_UPDATED",
    }
}